language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: kLlrVylZ+p3XlYEDpEi9qEPH5w1lubKFPRyx/2erihLLdg+R9oUuMJ6oETIORnd9OkpyUTPmky29vBz4AUfMjgkHnJm/aJEFtE8gO9JXBfb6XPBIuGbw7Mu41dEgnL52YVSxhDiAS1zZhrGMEWFl7VHreP090PlW9xNb6ASmEjm76IYIPZiajV6F5Ye9zBgu3IYm+h5o52qLqbyJTPi8xurzjGNnUTtx63kuWG/dXFEICZ4vXD7yG3CW/cSVMMRRHaqMp6cdGjaSmrgaze8+Ad+DzO58zX5q0JAKDsYI5txmHbVPrpveVzVimHSyLnRfqxEhxEgZsaVtaLT7whIPxSgLdnX1DLkp9wtFD0SzGapZqpFmfkqu8gDjSatJpnsniB5Krlgh8qT8E33XuBd56liUzQh/idfXPvVFgALiCTD5FT6zxmXWvf5QT9r8cxYG3T69MQvkUZvATL2LNE4raVTDW7pFyhAbjYA0Z7y2ElwW6zv//d+tWy12YGH8aYLIOLK5lAKPToH+bJcLTtiVYOzidX2lEhgoIjBS86m3N6MckN8oCOvIzcvfoqKsOeEO13DGKmq58x729ZH7/gXs+LhYd98T9sIG+B/MXFmKdhV7RyVCduGlOyNbmIkNcx06YtUkjE8ekITmLSGp2zhXCA9Tv8cEwl0oSqkPeDOp3j4=
  - secure: rUCeNsaXTQkHO4jysi0YFzDjkSb9hZbekpU4M2wKn+tv3PgURCeK+jkgyy2o4SEfolTp3trCtvbhN9OxNdZjFLAeuDvNOo1srtM6vN3HGlXOW+CcMgXtMwjAHEqEDrpi39l4Nn72xrHWh7ALvSrGfzMHN/zFp8T4VinhOPvsDONTBuK1fwSuDU0DNPOFBeSJ8z68feoG8IZGbVd9cLJVCYQcGTGmZs2r9qGg8xaUYTUuyWXW5YUvx1AVWn+RaLTJVsOdKVxYIaIfmIWFIWQSiE1Fr+Irpjo0ij7dEEiZ4/8h5H5VjA6LsVVgy+DfzkU4NhBwWhmbJ1hJw1qb6AqvzvJz0Y7V6vJuUTLtnrHcKrUXl6WNwByaHuklh09oUV9yaMeMhm5PCD0PPWYjJrETEb/vD68CGwOERrvQZ1/M+n+GuUtuleNO/mVyhjDnfgOmnhiJDbvh5D5U+0ZP04sRPKq1C179I6s3fc1qEgB0DBWxYpkS9xlvXrtX8WunfXlOvGeaat/IN0/+PQrwOIS0YY3c8GIREOsFEZKKL/nxRT8iPvE/hIDbdaECwl0pCuR7cygvlQrwf4iSVwKhL+uczsTt+0T5m2/YHjLnNbCm5BUQwUAbGi0o24QPVrlydwKpB6WwiwKoIOt9JEOL/G5erU9sqSCOUX6MpOOfcsTt69M=
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: amXG/RTH0SjSGiQiNvfVe48v3T0KpBkUOX0F4qJg+4CkC4UQpj8J+89T7pOhjAqugcTuFHepMGr9G+9yXlxOfrFBZP85QVLcDQSkujuI/BWDBAPw51SgHp51nb8d+z8aEcikS9Jr95E6Fa8gG6MCj3HGowXrRhPLsEvR+EV93Z3IBIHRIYgX8tPiT/eJXw1aNJzcDaiUZZUK3rQqf2DK5XixF5BfyPf3ISq8/R7wDkv9uXfBlCxRe4rLjJBjqkrw72csxyPya5zqZSKlwoK9+Mm2aBu0OkdfK7a3lxST5qjk+HVrfh9wXHYybfxu8Pp0EC73nYL+6xVHpJE7oU1N/70WndiWDmSxcyVN1M21L+SrIYrUt6tu4Pw8tf1psbndxZvfLcha6A260UxYsm4UwhhbJx/bc9Vhw9KpTZeuWYeU3dilu+4iHywpDR31pw0B5wSNBv1Uz3xWNoT4zl/XxhiDRO2eXSl0LVfBY5glh1uCjQE8wzV9BqJ1W9/YD0W/Y9KIM33kIaLBGph1oKa7nZVXSYB+hFOP2YMFxQLckfGPPajHQkYYfjU8aVo7xaQlON93ZD3UGOQHT7QUjYkg4qMhaY+kZ9eRjvLY5gsvAbwke7GSeJVTCR0X/chK/jbEvwhf1MGC61BOJnJntN3Z9kwBd0XXtta1bNxR6/91CK0=
  on:
    branch: master
    repo: plepers/nanogl-state
